######################################################
# pipeline_template.py configuration file
# Pipeline specific options into separate sections
# pipeline.yml
######################################################

# General options:
general:
    author_name:
    project_name:
    licence:
    version:

# Pipeline specific options:
#file holding GWAS data and pheno file
inp_file: sim_gwas

#Number of chromosome files (including sex chromsomes)
chr_number: 22

#title of each chromosome file
inp_title: chr

#title of GRM directory (made by pipeline)
GRM_dir: GRM

#title of asso directory (made by pipeline)
asso_dir: asso

#directory of phenotype file
pheno: sim_gwas/phe_n.phen

#cluster:
#    tmpdir: /tmp/